rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head

before_script:
  - psql -c 'create database rqd2_test;' -U postgres

env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"